# Generated by Django 6.0.7 on 2026-07-30 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.CharField(blank=True, max_length=500, null=True)),
                ('yt_username', models.CharField(blank=True, max_length=100, null=True)),
                ('insta_username', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman & Nicobar Islands (UT)'), ('CH', 'Chandigarh (UT)'), ('DN', 'Dadra & Nagar Haveli and Daman & Diu (UT)'), ('DL', 'Delhi (UT)'), ('JK', 'Jammu & Kashmir (UT)'), ('LA', 'Ladakh (UT)'), ('LD', 'Lakshadweep (UT)'), ('PY', 'Puducherry (UT)'), ('OTHER', 'Other / International')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('teaching_category', models.CharField(blank=True, choices=[('development', 'Software & Web Development'), ('data_science', 'Data Science & AI'), ('design', 'UI/UX & Graphic Design'), ('business', 'Business & Finance'), ('marketing', 'Digital Marketing'), ('personal_dev', 'Personal Development'), ('other', 'Other')], max_length=50, null=True)),
                ('experience', models.CharField(blank=True, choices=[('0-1', '0 - 1 Years'), ('1-3', '1 - 3 Years'), ('3-5', '3 - 5 Years'), ('5-10', '5 - 10 Years'), ('10+', '10+ Years')], max_length=20, null=True)),
                ('profession', models.CharField(blank=True, choices=[('software_engineer', 'Software Engineer / Developer'), ('data_scientist', 'Data Scientist / Analyst'), ('designer', 'Product / UI/UX Designer'), ('educator', 'Educator / Teacher'), ('content_creator', 'Content Creator / Influencer'), ('consultant', 'Consultant / Freelancer'), ('entrepreneur', 'Entrepreneur / Founder'), ('student', 'Student'), ('other', 'Other')], max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.CharField(blank=True, max_length=500, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman & Nicobar Islands (UT)'), ('CH', 'Chandigarh (UT)'), ('DN', 'Dadra & Nagar Haveli and Daman & Diu (UT)'), ('DL', 'Delhi (UT)'), ('JK', 'Jammu & Kashmir (UT)'), ('LA', 'Ladakh (UT)'), ('LD', 'Lakshadweep (UT)'), ('PY', 'Puducherry (UT)'), ('OTHER', 'Other / International')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('profession', models.CharField(blank=True, choices=[('software_engineer', 'Software Engineer / Developer'), ('data_scientist', 'Data Scientist / Analyst'), ('designer', 'Product / UI/UX Designer'), ('educator', 'Educator / Teacher'), ('content_creator', 'Content Creator / Influencer'), ('consultant', 'Consultant / Freelancer'), ('entrepreneur', 'Entrepreneur / Founder'), ('student', 'Student'), ('other', 'Other')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
