# Generated by Django 6.0.7 on 2026-08-05 21:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Course description (100-200 words)')),
                ('course_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Mandarin Chinese'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('te', 'Telugu'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('ur', 'Urdu'), ('gu', 'Gujarati'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('or', 'Odia'), ('pa', 'Punjabi')], default='en', max_length=5)),
                ('course_thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
