# Generated by Django 6.0.7 on 2026-08-06 20:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorcourse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('29.00'), help_text='Course price in INR (minimum ₹29)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('29.00'))]),
        ),
        migrations.AlterField(
            model_name='creatorcourse',
            name='course_name',
            field=models.CharField(max_length=80),
        ),
    ]
