# Generated by Django 6.0.7 on 2026-08-06 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_creatorcourse_price_alter_creatorcourse_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorcourse',
            name='course_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='creatorcourse',
            name='price',
            field=models.IntegerField(default=29, help_text='Course price in INR (minimum ₹29)', validators=[django.core.validators.MinValueValidator(29)]),
        ),
    ]
