# Generated by Django 6.0.7 on 2026-08-06 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_creatorcourse_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorcourse',
            name='price',
            field=models.IntegerField(default=29, help_text='Course price in INR (minimum ₹29, maximum ₹9999)', validators=[django.core.validators.MinValueValidator(29), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
