# Generated by Django 6.0.7 on 2026-08-09 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_creatorcourse_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('module_title', models.CharField(max_length=255)),
                ('what_you_will_learn', models.TextField(blank=True, help_text='Key takeaways and learning objectives for this module', null=True)),
                ('module_thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('module_video', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_in_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the video in seconds')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order/position of the module in the course')),
                ('is_preview', models.BooleanField(default=False, help_text='Whether this module is available as a free preview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.creatorcourse')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
